"""empty message

Revision ID: 9f531f83deb7
Revises: 
Create Date: 2021-10-04 20:33:34.866265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f531f83deb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_permissao',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('tb_vinculo_permissao_funcao',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('id_permissao', sa.BigInteger(), nullable=True),
    sa.Column('id_funcao', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id_permissao'], ['tb_permissao.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_funcao')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_vinculo_permissao_funcao')
    op.drop_table('tb_permissao')
    # ### end Alembic commands ###
