"""empty message

Revision ID: 0b71e18a1efe
Revises: ed2042d44739
Create Date: 2022-04-10 02:18:31.437691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b71e18a1efe'
down_revision = 'ed2042d44739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_arquivo', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('tb_arquivo', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_arquivo', 'file_name')
    op.drop_column('tb_arquivo', 'file_type')
    # ### end Alembic commands ###
