"""empty message

Revision ID: 23fff556207e
Revises: 9f531f83deb7
Create Date: 2021-10-04 20:41:08.184892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fff556207e'
down_revision = '9f531f83deb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_vinculo_permissao_funcao_id_funcao_key', 'tb_vinculo_permissao_funcao', type_='unique')
    op.create_unique_constraint(None, 'tb_vinculo_permissao_funcao', ['id_permissao', 'id_funcao'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_vinculo_permissao_funcao', type_='unique')
    op.create_unique_constraint('tb_vinculo_permissao_funcao_id_funcao_key', 'tb_vinculo_permissao_funcao', ['id_funcao'])
    # ### end Alembic commands ###
