"""empty message

Revision ID: 3d003c75945e
Revises: 2052028b50fb
Create Date: 2021-10-24 10:33:57.740193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d003c75945e'
down_revision = '2052028b50fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tb_perfil_id_entidade_email_fkey', 'tb_perfil', type_='foreignkey')
    op.drop_constraint('tb_perfil_id_entidade_phone_fkey', 'tb_perfil', type_='foreignkey')
    op.drop_column('tb_perfil', 'id_entidade_phone')
    op.drop_column('tb_perfil', 'id_entidade_email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_perfil', sa.Column('id_entidade_email', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('tb_perfil', sa.Column('id_entidade_phone', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('tb_perfil_id_entidade_phone_fkey', 'tb_perfil', 'tb_perfil_phone', ['id_entidade_phone'], ['id'])
    op.create_foreign_key('tb_perfil_id_entidade_email_fkey', 'tb_perfil', 'tb_perfil_email', ['id_entidade_email'], ['id'])
    # ### end Alembic commands ###
