"""empty message

Revision ID: 46b736b6108a
Revises: 3d003c75945e
Create Date: 2021-10-24 11:45:48.834158

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46b736b6108a'
down_revision = '3d003c75945e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_perfil_email', sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'tb_perfil_email', ['guid'])
    op.create_foreign_key(None, 'tb_perfil_email', 'tb_perfil', ['id_perfil'], ['id'])
    op.add_column('tb_perfil_phone', sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_unique_constraint(None, 'tb_perfil_phone', ['guid'])
    op.create_foreign_key(None, 'tb_perfil_phone', 'tb_perfil', ['id_perfil'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_perfil_phone', type_='foreignkey')
    op.drop_constraint(None, 'tb_perfil_phone', type_='unique')
    op.drop_column('tb_perfil_phone', 'guid')
    op.drop_constraint(None, 'tb_perfil_email', type_='foreignkey')
    op.drop_constraint(None, 'tb_perfil_email', type_='unique')
    op.drop_column('tb_perfil_email', 'guid')
    # ### end Alembic commands ###
