"""empty message

Revision ID: d8a0df8e1216
Revises: 46b736b6108a
Create Date: 2021-10-24 19:18:45.506889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a0df8e1216'
down_revision = '46b736b6108a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_perfil', sa.Column('nome_exibicao_normalized', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_perfil', 'nome_exibicao_normalized')
    # ### end Alembic commands ###
