"""empty message

Revision ID: fdcca6e34330
Revises: 70464fb29418
Create Date: 2021-12-02 00:06:41.740427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdcca6e34330'
down_revision = '70464fb29418'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_perfil', sa.Column('url_imagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_perfil', 'url_imagem')
    # ### end Alembic commands ###
