"""empty message

Revision ID: ed2042d44739
Revises: fdcca6e34330
Create Date: 2022-04-10 01:50:08.600506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed2042d44739'
down_revision = 'fdcca6e34330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_arquivo',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guid')
    )
    op.add_column('tb_perfil', sa.Column('id_imagem_perfil', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'tb_perfil', 'tb_arquivo', ['id_imagem_perfil'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_perfil', type_='foreignkey')
    op.drop_column('tb_perfil', 'id_imagem_perfil')
    op.drop_table('tb_arquivo')
    # ### end Alembic commands ###
